root@lux:/var/www/lux-marketing# # On VPS - Check the contacts page error
journalctl -u lux-marketing.service -n 50 --no-pager | grep -A 20 "Error\|Traceback" | tail -40
Oct 21 07:34:31 lux gunicorn[1337]:     raise BuildError(endpoint, values, method, self)
Oct 21 07:34:31 lux gunicorn[1337]: werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.add_contact'. Did you mean 'main.contacts' instead?
Oct 21 07:34:33 lux gunicorn[1336]: ERROR:app:Exception on /contacts [GET]
Oct 21 07:34:33 lux gunicorn[1336]: Traceback (most recent call last):
Oct 21 07:34:33 lux gunicorn[1336]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
Oct 21 07:34:33 lux gunicorn[1336]:     response = self.full_dispatch_request()
Oct 21 07:34:33 lux gunicorn[1336]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 21 07:34:33 lux gunicorn[1336]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
Oct 21 07:34:33 lux gunicorn[1336]:     rv = self.handle_user_exception(e)
Oct 21 07:34:33 lux gunicorn[1336]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 21 07:34:33 lux gunicorn[1336]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
Oct 21 07:34:33 lux gunicorn[1336]:     rv = self.dispatch_request()
Oct 21 07:34:33 lux gunicorn[1336]:          ^^^^^^^^^^^^^^^^^^^^^^^
Oct 21 07:34:33 lux gunicorn[1336]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
Oct 21 07:34:33 lux gunicorn[1336]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
Oct 21 07:34:33 lux gunicorn[1336]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 21 07:34:33 lux gunicorn[1336]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
Oct 21 07:34:33 lux gunicorn[1336]:     return current_app.ensure_sync(func)(*args, **kwargs)
Oct 21 07:34:33 lux gunicorn[1336]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 21 07:34:33 lux gunicorn[1336]:   File "/var/www/lux-marketing/routes.py", line 40, in contacts
Oct 21 07:34:33 lux gunicorn[1336]:     return render_template('contacts.html', contacts=contacts)
Oct 21 07:34:33 lux gunicorn[1336]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 21 07:34:33 lux gunicorn[1336]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
Oct 21 07:34:33 lux gunicorn[1336]:     return _render(app, template, context)
--
Oct 21 07:34:33 lux gunicorn[1336]:     raise BuildError(endpoint, values, method, self)
Oct 21 07:34:33 lux gunicorn[1336]: werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.add_contact'. Did you mean 'main.contacts' instead?