
Fixed! Now go to https://lux.lucifercruz.com/automations
root@lux:/var/www/lux-marketing# # On VPS - Check the latest error
journalctl -u lux-marketing.service -n 40 --no-pager | grep -A 15 "ERROR\|Traceback"
root@lux:/var/www/lux-marketing# journalctl -u lux-marketing.service -n 20 --no-pager
Oct 21 09:34:42 lux gunicorn[2522]:     rv = template.render(context)
Oct 21 09:34:42 lux gunicorn[2522]:          ^^^^^^^^^^^^^^^^^^^^^^^^
Oct 21 09:34:42 lux gunicorn[2522]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
Oct 21 09:34:42 lux gunicorn[2522]:     self.environment.handle_exception()
Oct 21 09:34:42 lux gunicorn[2522]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
Oct 21 09:34:42 lux gunicorn[2522]:     raise rewrite_traceback_stack(source=source)
Oct 21 09:34:42 lux gunicorn[2522]:   File "/var/www/lux-marketing/templates/automations.html", line 1, in top-level template code
Oct 21 09:34:42 lux gunicorn[2522]:     {% extends "base.html" %}
Oct 21 09:34:42 lux gunicorn[2522]:   File "/var/www/lux-marketing/templates/base.html", line 53, in top-level template code
Oct 21 09:34:42 lux gunicorn[2522]:     <li><a class="dropdown-item" href="{{ url_for('main.automation_dashboard') }}">Automation</a></li>
Oct 21 09:34:42 lux gunicorn[2522]:     ^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 21 09:34:42 lux gunicorn[2522]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/flask/app.py", line 1121, in url_for
Oct 21 09:34:42 lux gunicorn[2522]:     return self.handle_url_build_error(error, endpoint, values)
Oct 21 09:34:42 lux gunicorn[2522]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 21 09:34:42 lux gunicorn[2522]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/flask/app.py", line 1110, in url_for
Oct 21 09:34:42 lux gunicorn[2522]:     rv = url_adapter.build(  # type: ignore[union-attr]
Oct 21 09:34:42 lux gunicorn[2522]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 21 09:34:42 lux gunicorn[2522]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
Oct 21 09:34:42 lux gunicorn[2522]:     raise BuildError(endpoint, values, method, self)
Oct 21 09:34:42 lux gunicorn[2522]: werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.automation_dashboard'. Did you mean 'main.automations' instead?